spring:
  datasource:
    url: jdbc:sqlite:D:/database/ebms/ebms.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

