spring:
  datasource:
    url: jdbc:sqlite:C:/Users/Sourav/eclipse-workspace/demo/database/dummy.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create

